### PR TITLE
Add fact command

### PR DESCRIPTION
**Pull request by lleytonvs**
This PR is for a re-implementation of the two (cat, java) fact commands, provided as sub-commands.

### CODE REVIEW

**Review by Wolfleader101 — APPROVED** [review]
I love the command and the implementation.

A few tips - but I won't disapprove of the pr.

When writing async methods, you don't need to add .then instead you can do the following

```js

const res= await axios.get("https://catfact.ninja/fact");

return res.data.fact;

```

I would recommend using `node-fetch` over Axios as it replicates the native fetch API for node.js and is much cleaner, imo. 

This would be rewritten as


```js

const res = await  fetch("https://catfact.ninja/fact")
const data = await json(res);
return data.fact;

```

**Comment by lleytonvs** [comment]
> I would recommend using `node-fetch` over Axios as it replicates the native fetch API for node.js and is much cleaner, imo.

I tried `node-fetch@3.2.3` but ran into issues related imports due to our use of `commonjs` for the [TypeScript compiler's module system.](https://www.typescriptlang.org/tsconfig#module) I decided to use Axios as I didn't want to use the downgraded 2.x version.

**Comment by giodotblue** [comment]
node-fetch comes with discord.js just use `import fetch from 'node-fetch'`

**Comment by lleytonvs** [comment]
Just realised I forgot to stage the changes for `package.json` in my commit, so `axios` isn't listed as a dependency.

**Pull request merged**
